test: featuretest script: added SKIP_TEST env var, for skip first N tests

diff --git a/tests/features/featuretest b/tests/features/featuretest
--- a/tests/features/featuretest
+++ b/tests/features/featuretest
@@ -22,14 +22,19 @@ fi
 SPLIT_INDEX=${SPLIT_INDEX:-"0"}
 SPLIT_TOTAL=${SPLIT_TOTAL:-"1"}
 
+#skip the first n tests
+SKIP_TESTS=${SKIP_TESTS:-"0"}
+
 exitcode=0
+
+testindex=0
 
 # test procedure that is run for each test case (assumes to be in INET_ROOT)
 runtest() {
-  (make makefiles >/dev/null && make cleanall >/dev/null && make makefiles >/dev/null) || { echo "*** $1 prepare build: FAIL" ; return 1; }
-  make -j8 >/$LOG_DIR/$1-build.out 2>/$LOG_DIR/$1-build.err || { echo "*** $1 building: FAIL" ; return 1; }
-  (cd $DIR; opp_run -l ../../src/INET -u Cmdenv -n ../../src:. >/$LOG_DIR/$1-run.out 2>/$LOG_DIR/$1-run.err) || { echo "*** $1 running: FAIL" ; return 1; }
-  echo "*** $1: PASS"; return 0;
+  (make makefiles >/dev/null && make cleanall >/dev/null && make makefiles >/dev/null) || { echo "*** $testindex. $1 prepare build: FAIL" ; return 1; }
+  make -j8 >/$LOG_DIR/$1-build.out 2>/$LOG_DIR/$1-build.err || { echo "*** $testindex. $1 building: FAIL" ; return 1; }
+  (cd $DIR; opp_run -l ../../src/INET -u Cmdenv -n ../../src:. >/$LOG_DIR/$1-run.out 2>/$LOG_DIR/$1-run.err) || { echo "*** $testindex. $1 running: FAIL" ; return 1; }
+  echo "*** $testindex. $1: PASS"; return 0;
 }
 
 cd `dirname $0`
@@ -51,31 +56,45 @@ fi
 if [ "$SPLIT_INDEX" = "0" ]; then
 
   # test with all features disabled
-  ./bin/inet_featuretool -q disable -f all
-  runtest all_disabled
-  if [ $? != 0 ]; then exitcode=1; fi
+  if [ "$testindex" -lt "$SKIP_TESTS" ] ; then
+    echo "*** all_disabled: SKIPPED"
+  else
+    ./bin/inet_featuretool -q disable -f all
+    runtest all_disabled
+    if [ $? != 0 ]; then exitcode=1; fi
+  fi
+  testindex=$((testindex+1))
 
   # test with default features enabled (except skipped ones)
-  ./bin/inet_featuretool -q reset
-  if [ -n "$skipped_features" ]; then
-    ./bin/inet_featuretool -q disable -f $skipped_features
+  if [ "$testindex" -lt "$SKIP_TESTS" ] ; then
+    echo "*** default: SKIPPED"
+  else
+    ./bin/inet_featuretool -q reset
+    if [ -n "$skipped_features" ]; then
+      ./bin/inet_featuretool -q disable -f $skipped_features
+    fi
+    runtest default
+    if [ $? != 0 ]; then exitcode=1; fi
   fi
-  runtest default
-  if [ $? != 0 ]; then exitcode=1; fi
+  testindex=$((testindex+1))
 
   # test with all features enabled (except skipped ones)
-  ./bin/inet_featuretool -q enable -f all
-  if [ -n "$skipped_features" ]; then
-    ./bin/inet_featuretool -q disable -f $skipped_features
+  if [ "$testindex" -lt "$SKIP_TESTS" ] ; then
+    echo "*** all_enabled: SKIPPED"
+  else
+    ./bin/inet_featuretool -q enable -f all
+    if [ -n "$skipped_features" ]; then
+      ./bin/inet_featuretool -q disable -f $skipped_features
+    fi
+    runtest all_enabled
+    if [ $? != 0 ]; then exitcode=1; fi
   fi
-  runtest all_enabled
-  if [ $? != 0 ]; then exitcode=1; fi
-
+  testindex=$((testindex+1))
 fi
 
 # test with each feature enabled - one by one
 for feature in $base_features; do
-  if echo $skipped_features | grep -q $feature; then
+  if echo $skipped_features | grep -q $feature || [ "$testindex" -lt "$SKIP_TESTS" ] ; then
     echo "*** ${feature}_enabled: SKIPPED"
   else
     ./bin/inet_featuretool -q disable -f all
@@ -83,12 +102,13 @@ for feature in $base_features; do
     runtest ${feature}_enabled
     if [ $? != 0 ]; then exitcode=1; fi
   fi
+  testindex=$((testindex+1))
 done
 
 # test with each feature disabled - one by one
 for feature in $base_features; do
   ./bin/inet_featuretool -q enable -f all
-  if [ -n "$skipped_features" ]; then
+  if [ -n "$skipped_features" || [ "$testindex" -lt "$SKIP_TESTS" ] ; then
     ./bin/inet_featuretool -q disable -f $skipped_features
   fi
   if echo $skipped_features | grep -q $feature; then
@@ -98,6 +118,7 @@ for feature in $base_features; do
     runtest ${feature}_disabled
     if [ $? != 0 ]; then exitcode=1; fi
   fi
+  testindex=$((testindex+1))
 done
 
 exit $exitcode
